title: Critical Coding II

baseurl: ""

# Build settings
markdown: kramdown

# Local dev settings
port: 6300

collections:
  pages:
    output: true
    permalink: :path/

# Defaults
defaults:
  - scope:
      type: "pages"
    values:
      layout: "page"
